---
title: "Project"
author: "Jonathan Rosenblatt"
date: "March 24, 2015"
output: html_document
---

[Under construction. Please revisit and expect updates.]
____

Here are the guidelines for the course's concluding project.
The project is based on [Kaggle's]() competitions.
You will be required to pick one of 5 competitions, submit an entry, and report the process.

# Dates
Teaming up: no later than _27.4.2015_.
Submission data: no later than _26.6.2015_.

Recommended time-table:

1. During the Passover vacation, go over the different competitions. Download the data. Make sure you can load it. 
2. After Passover, find your partner and project and notify me.
3. Don't wait until the last minute! [This](http://www-bcf.usc.edu/~gareth/ISL/) is an easy reference to start reading for yourself. [This](http://statweb.stanford.edu/~tibs/ElemStatLearn/) is a more advanced reference. Once you picked your project, I can point to the appropriate chapters.



# Guidelines

1. Open an account at [Kaggle](https://www.kaggle.com/).
2. Pick one of the "Playground" competitions and compete! These are: 
  - [Billion Word Imputations](https://www.kaggle.com/c/billion-word-imputation).
  - [Forest Cover Type Prediction](https://www.kaggle.com/c/forest-cover-type-prediction).
  - [Bike Sharing Demand](https://www.kaggle.com/c/bike-sharing-demand) (recommended). 
  - [Random Acts of Pizza](https://www.kaggle.com/c/random-acts-of-pizza).
  - [Poker Rule Induction](https://www.kaggle.com/c/poker-rule-induction).
3. Write a report documenting the process.
  - No longer than 8 pages (not including appendices).
  - Should contain the sections:
    - Background: Some background on the competition. 
    - Scoring: The scoring criterion in the competition. What loss function with what data?
    - The data: What data was provided for learning? What files in what formats? Which variables? How did you handle them?
    - Algorithms: Which learning algorithms did you try?
    - Results: What score did you achieve? What was your ranking in the competition?
    - Discussion: Why were you successful/unsuccessful? What other ideas would you have liked to try? What were the major challenges? 
    
