---
title: "Graphics"
author: "Jonathan Rosenblatt"
date: "June 7, 2015"
output: html_document
---

The scripts producing the graphics in the class notes.


# Imputing missing data
Create complete data
```{r create}
n <- 20
noise <- rnorm(n*2) %>% matrix(ncol=2) 
signal <- outer(rexp(n,1/2),c(1,1)) %>% scale
x <- signal + noise 
x.range <- 1.1* range(x[,1]); y.range <- 1.1* range(x[,2])
plot(signal, xlab='Movie 1', ylab='Movie 2', xlim = x.range, ylim = y.range)
points(x, pch=19)
arrows(x0=signal[,1], y0=signal[,2], x1=x[,1], y1=x[,2], col='darkgrey')
```

Then censor some points
```{r censor}
censoring.ind <- cbind(1:n, sample(c(NA,1,2), n, replace=TRUE, prob = c(2,1,1)))
x.censored <- x
x.censored[censoring.ind] <- NA
points(x.censored, col='red', pch=19) # Observed points
#So this is what we know
x.censored.1.ind <- (censoring.ind[,2]==1) %>% sapply(isTRUE)
x.censored.2.ind <- (censoring.ind[,2]==2) %>% sapply(isTRUE)
# plot(x.censored)
abline(h=x.censored[x.censored.1.ind,2], lty=2)
abline(v=x.censored[x.censored.2.ind,1], lty=2)
```


Let's try to impute using a 1D linear space embedding and reconstruction:
```{r}
x.censored.clean <- x.censored %>% na.omit
svd.1 <- x.censored.clean  %>% svd
d.2 <- diag(svd.1$d)
d.2[2,2] <- 0
x.censored.reduced <- svd.1$u %*% d.2 %*% t(svd.1$v)
points(x.censored.reduced, col='green', pch=19)
lm.1 <- lm(x.censored.reduced[,2]~x.censored.reduced[,1])
abline(lm.1, col='darkgreen')
```






